chaning back to normal

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -173,87 +173,87 @@ jobs:
           echo "ec2_linux_itar_matrix: ${{ steps.set-matrix.outputs.ec2_linux_itar_matrix }}"
           echo "ec2_linux_china_matrix: ${{ steps.set-matrix.outputs.ec2_linux_china_matrix }}"
 
-  #
-  #  EC2WinIntegrationTest:
-  #    needs: [BuildAndUpload, BuildAndUploadPackages, GenerateTestMatrix]
-  #    name: 'EC2WinIntegrationTest'
-  #    runs-on: ubuntu-latest
-  #    strategy:
-  #      fail-fast: false
-  #      matrix:
-  #        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.ec2_windows_matrix) }}
-  #    permissions:
-  #      id-token: write
-  #      contents: read
-  #    steps:
-  #      - uses: actions/checkout@v3
-  #        with:
-  #          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-  #          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
-  #
-  #      - name: Configure AWS Credentials
-  #        uses: aws-actions/configure-aws-credentials@v2
-  #        with:
-  #          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-  #          aws-region: us-west-2
-  #          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}
-  #
-  #      - name: Cache if success
-  #        id: ec2-win-integration-test
-  #        uses: actions/cache@v3
-  #        with:
-  #          path: go.mod
-  #          key: ec2-win-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
-  #
-  #      - name: Echo Test Info
-  #        run: echo run on ec2 instance os ${{ matrix.arrays.os }} use ssm ${{ matrix.arrays.useSSM }} test ${{ matrix.arrays.test_dir }}
-  #
-  #      - name: Verify Terraform version
-  #        run: terraform --version
-  #
-  #        # nick-fields/retry@v2 starts at base dir
-  #      - name: Terraform apply
-  #        uses: nick-fields/retry@v2
-  #        with:
-  #          max_attempts: 3
-  #          timeout_minutes: 30
-  #          retry_wait_seconds: 5
-  #          command: |
-  #            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
-  #              cd "${{ matrix.arrays.terraform_dir }}"
-  #            else
-  #              cd terraform/ec2/win
-  #            fi
-  #            terraform init
-  #            if terraform apply --auto-approve \
-  #            -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
-  #            -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}"  \
-  #            -var="test_name=${{ matrix.arrays.os }}" \
-  #            -var="cwa_github_sha=${GITHUB_SHA}"  \
-  #            -var="test_dir=${{ matrix.arrays.test_dir }}" \
-  #            -var="ami=${{ matrix.arrays.ami }}" \
-  #            -var="use_ssm=${{ matrix.arrays.useSSM }}" \
-  #            -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then
-  #              terraform destroy -auto-approve
-  #            else
-  #              terraform destroy -auto-approve && exit 1
-  #            fi
-  #
-  #      #This is here just in case workflow cancel
-  #      - name: Terraform destroy
-  #        if: ${{ cancelled() || failure() }}
-  #        uses: nick-fields/retry@v2
-  #        with:
-  #          max_attempts: 3
-  #          timeout_minutes: 8
-  #          retry_wait_seconds: 5
-  #          command: |
-  #            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
-  #              cd "${{ matrix.arrays.terraform_dir }}"
-  #            else
-  #              cd terraform/ec2/win
-  #            fi
-  #            terraform destroy --auto-approve
+
+  EC2WinIntegrationTest:
+    needs: [BuildAndUpload, BuildAndUploadPackages, GenerateTestMatrix]
+    name: 'EC2WinIntegrationTest'
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.ec2_windows_matrix) }}
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+          aws-region: us-west-2
+          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}
+
+      - name: Cache if success
+        id: ec2-win-integration-test
+        uses: actions/cache@v3
+        with:
+          path: go.mod
+          key: ec2-win-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
+
+      - name: Echo Test Info
+        run: echo run on ec2 instance os ${{ matrix.arrays.os }} use ssm ${{ matrix.arrays.useSSM }} test ${{ matrix.arrays.test_dir }}
+
+      - name: Verify Terraform version
+        run: terraform --version
+
+        # nick-fields/retry@v2 starts at base dir
+      - name: Terraform apply
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 30
+          retry_wait_seconds: 5
+          command: |
+            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
+              cd "${{ matrix.arrays.terraform_dir }}"
+            else
+              cd terraform/ec2/win
+            fi
+            terraform init
+            if terraform apply --auto-approve \
+            -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
+            -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}"  \
+            -var="test_name=${{ matrix.arrays.os }}" \
+            -var="cwa_github_sha=${GITHUB_SHA}"  \
+            -var="test_dir=${{ matrix.arrays.test_dir }}" \
+            -var="ami=${{ matrix.arrays.ami }}" \
+            -var="use_ssm=${{ matrix.arrays.useSSM }}" \
+            -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then
+              terraform destroy -auto-approve
+            else
+              terraform destroy -auto-approve && exit 1
+            fi
+
+      #This is here just in case workflow cancel
+      - name: Terraform destroy
+        if: ${{ cancelled() || failure() }}
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 5
+          command: |
+            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
+              cd "${{ matrix.arrays.terraform_dir }}"
+            else
+              cd terraform/ec2/win
+            fi
+            terraform destroy --auto-approve
 
   EC2DarwinIntegrationTest:
     needs: [BuildAndUpload, BuildAndUploadPackages, GenerateTestMatrix]
@@ -267,8 +267,7 @@ jobs:
       id-token: write
       contents: read
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3
         with:
           repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
           ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
@@ -288,11 +287,12 @@ jobs:
           key: ec2-mac-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
 
       - name: Echo OS
-        run: echo "run on ec2 instance os ${{ matrix.arrays.os }}"
+        run: echo run on ec2 instance os ${{ matrix.arrays.os }}
 
       - name: Verify Terraform version
         run: terraform --version
 
+        # nick-fields/retry@v2 starts at base dir
       - name: Terraform apply
         uses: nick-fields/retry@v2
         with:
@@ -306,32 +306,31 @@ jobs:
               cd terraform/ec2/mac
             fi
             terraform init
-            terraform apply --auto-approve \
-              -var="ssh_key_value=${PRIVATE_KEY}" \
-              -var="ssh_key_name=${KEY_NAME}"  \
-              -var="arc=${{ matrix.arrays.arc }}" \
-              -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
-              -var="cwa_github_sha=${GITHUB_SHA}" \
-              -var="ami=${{ matrix.arrays.ami }}" \
-              -var="test_dir=${{ matrix.arrays.test_dir }}" \
-              -var="license_manager_arn=${{ env.LICENSE_MANAGER_ARN }}" \
-              -var="s3_bucket=${S3_INTEGRATION_BUCKET}"
-
-      
+            if terraform apply --auto-approve \
+            -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}"  \
+            -var="arc=${{ matrix.arrays.arc }}" \
+            -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
+            -var="cwa_github_sha=${GITHUB_SHA}" -var="ami=${{ matrix.arrays.ami }}" \
+            -var="test_dir=${{ matrix.arrays.test_dir }}" \
+            -var="license_manager_arn=${{ env.LICENSE_MANAGER_ARN }}" \
+            -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then
+              terraform destroy -auto-approve
+            else
+              terraform destroy -auto-approve && exit 1
+            fi
 
       #This is here just in case workflow cancel
-#      - name: Terraform destroy
-#        if: ${{ cancelled() || failure() }}
-#        uses: nick-fields/retry@v2
-#        with:
-#          max_attempts: 3
-#          timeout_minutes: 8
-#          retry_wait_seconds: 5
-#          command: |
-#            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
-#              cd "${{ matrix.arrays.terraform_dir }}"
-#            else
-#              cd terraform/ec2/mac
-#            fi
-#            terraform destroy --auto-approve
-
+      - name: Terraform destroy
+        if: ${{ cancelled() || failure() }}
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 5
+          command: |
+            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
+              cd "${{ matrix.arrays.terraform_dir }}"
+            else
+              cd terraform/ec2/mac
+            fi
+            terraform destroy --auto-approve
